name: Updater for Notion that can be hosted within Home Assistant OS
description: Updater for Notion that can be hosted within Home Assistant OS
version: '1.0.0'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
slug: notion_updater
init: false
startup: application
map:
  - share:rw

options:
  access_token: access_token
  journal_db_id: journal_db_id

schema:
  access_token: str
  journal_db_id: str
